name: real
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1
  convex_bottom_bar: ^3.2.0
  intl: ^0.20.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    #- assets/images/ktechLogo.png
    - assets/images/
    - assets/.
    #- assets/model_classification.tflite  # Add the exact path to your model
    #- assets/labels.txt  # Add the exact path to your labels
  #   - images/a_dot_ham.jpeg
